config/routes.rb
Rails.application.routes.draw do
  resources :nonis

  root to: "nonis#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/noni.rb
class Noni < ApplicationRecord
	def index
		
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/nonis_controller.rb
class NonisController < ApplicationController
  before_action :set_noni, only: %i[ show edit update destroy ]

  # GET /nonis or /nonis.json
  def index
    @nonis = Noni.all
  end

  # GET /nonis/1 or /nonis/1.json
  def show
  end

  # GET /nonis/new
  def new
    @noni = Noni.new
  end

  # GET /nonis/1/edit
  def edit
  end

  # POST /nonis or /nonis.json
  def create
    @noni = Noni.new(noni_params)

    respond_to do |format|
      if @noni.save
        format.html { redirect_to noni_url(@noni), notice: "Noni was successfully created." }
        format.json { render :show, status: :created, location: @noni }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @noni.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nonis/1 or /nonis/1.json
  def update
    respond_to do |format|
      if @noni.update(noni_params)
        format.html { redirect_to noni_url(@noni), notice: "Noni was successfully updated." }
        format.json { render :show, status: :ok, location: @noni }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @noni.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nonis/1 or /nonis/1.json
  def destroy
    @noni.destroy

    respond_to do |format|
      format.html { redirect_to nonis_url, notice: "Noni was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_noni
      @noni = Noni.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def noni_params
      params.fetch(:noni, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nonis_helper.rb
module NonisHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeLoveNoni</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'marketing', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
  </body>
</html>

app/views/nonis/_form.html.erb
<%= form_with(model: noni) do |form| %>
  <% if noni.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(noni.errors.count, "error") %> prohibited this noni from being saved:</h2>

      <ul>
        <% noni.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/nonis/_section1.slim
section.hero.theme-bg
  .wrapper-noni
    .logo-h
      div
        img[src="assets/logo.svg"]
      div.web-title
        | 
        b ADOMÁNYOZZ 
        br
         b | TE IS 
         span
          | NONIVAL!
    .on-mobile-content.text-center
      img[src="assets/picture.png"]
    .left-area
      .sub-head
        | RENDELJ ÉS TÁMOGASS!
      
      .head-para
        p
          | Szeretnéd támogatni a <b>Kutya-segélyszolgálat Alapítvány</b> munkáját, miközben a saját kutyád egészségéért is sokat teszel?

        p Óriási öröm számomra, hogy ez végre lehetővé vált! A weboldal bármely termékének megvásárlásával adományt küldesz a sérült, beteg kutyáink részére, miközben segítesz megőrizni kedvenced jó közérzetét, ízületeinek egészségét, valamint te is élvezheted a több mint 2000 éve használt polinéz gyógynövény jótékony hatásait.
    .bottom-image
      img[src="assets/dog1.svg"]
      img[src="assets/dog2.svg"]
      img.on-desktop-content[src="assets/dog3.svg"]
    .on-mobile-content
      img.set-b-img[src="assets/bottle.png"]
  .base-right-banner
    .mobile-images
      img.right-in[src="assets/right-leaf.png"]
      img.left-in[src="assets/left-leaf.png"]
    img.right-image[src="assets/dogs-love-noni.png"]

section.on-mobile-content
  .hero-mobile
    p
      | Szeretnéd támogatni a <b>Kutya-segélyszolgálat Alapítvány</b> munkáját, miközben a saját kutyád egészségéért is sokat teszel?

    p Óriási öröm számomra, hogy ez végre lehetővé vált! A weboldal bármely termékének megvásárlásával adományt küldesz a sérült, beteg kutyáink részére, miközben segítesz megőrizni kedvenced jó közérzetét, ízületeinek egészségét, valamint te is élvezheted a több mint 2000 éve használt polinéz gyógynövény jótékony hatásait.

section.on-mobile-content.b-image
  img.full-w[src="assets/with-dog.png"]






/ .section1
  .image-heading
    
  .parahs
    p Szeretnéd támogatni a Kutya-segélyszolgálat Alapítvány munkáját, miközben a saját kutyád egészségéért is sokat teszel?
    p Óriási öröm számomra, hogy ez végre lehetővé vált! A weboldal bármely termékének megvásárlásával adományt küldesz a sérült, beteg kutyáink részére, miközben segítesz megőrizni kedvenced jó közérzetét, ízületeinek egészségét, valamint te is élvezheted a több mint 2000 éve használt polinéz gyógynövény jótékony hatásait.
  
  

app/views/nonis/_section2.slim
section.vasarlas
  .wrapper-noni
    .common-heading.text-center
      | VÁSÁRLÁS



    .vasarlas_child.on-desktop-content
      .vasarlas__inner
        .head-title
          img[src="assets/bubble.png"]
        .vasarlas_img_inner
          img[src="assets/sec2-img1.png"]
        .vasarlas__text 
          .prod-name
            p DOGS LOVE NONI 2db
            p glükozaminnal, kondroitin-<br> szulfáttal és vitaminokkal 
          .prod-info
            p Kiszerelés: <b> 2x 750 mL/doboz</b>
            p támogatás összege: <div class="font-26 theme-text-red"><b>4.000 ft</b></div>
          .mtb-20.text-center.font-26 
            | Ár: 29.900 Ft
          p.font-14.theme-text-white.text-center.mh-70
            | + kiszállítási díj, mely a <br/>  kosár tartalmához kerül <br/> hozzáadásra (2.100 Ft)
          .text-center
            button.btn-theme-primary KOSÁRBA
      
      .vasarlas__inner
        .head-title
          img[src="assets/bubble.png"]
        .vasarlas_img_inner
          img[src="assets/sec2-img2.png"]
        .vasarlas__text 
          .prod-name
            p DOGS LOVE NONI 4db
            p glükozaminnal, kondroitin-<br> szulfáttal és vitaminokkal 
          .prod-info
            p Kiszerelés: <b> 4x 750 mL/doboz</b>
            p támogatás összege: <div class="font-26 theme-text-red"><b>8.000 ft</b></div>
          .mtb-20.text-center.font-26
            | Ár: 57.900 Ft
          p.font-14.theme-text-white.text-center.mh-70
            | Ingyenes kiszállítás!
          .text-center
            button.btn-theme-primary KOSÁRBA
      

      .vasarlas__inner
        .head-title
          img[src="assets/bubble-2.png"]
        .vasarlas_img_inner
          img[src="assets/sec2-img3.png"]
        .vasarlas__text 
          .prod-name.line-blue
            p MAGICAL LOVE NONI 2db
            p vörös szőlővel és<br> kék áfonyával 
          .prod-info
            p Kiszerelés: <b> 4x 750 mL/doboz</b>
            p támogatás összege: <div class="font-26 theme-text-blue"><b>7.200 ft</b></div>
          .mtb-20.text-center.font-26
            | Ár: 52.800 Ft
          p.font-14.theme-text-white.text-center.mh-70
            | + kiszállítási díj, mely a <br/> kosár tartalmához kerül <br/> hozzáadásra (2.200 Ft)
          .text-center
            button.btn-theme-secondary KOSÁRBA


    .on-mobile-content
      #carouselExampleControls.carousel.slide[data-ride="carousel" data-interval="100000"]
        ol.carousel-indicators
          li.active[data-target="#carouselExampleControls" data-slide-to="0"]
          li[data-target="#carouselExampleControls" data-slide-to="1"]
          li[data-target="#carouselExampleControls" data-slide-to="2"]
        .carousel-inner.vasarlas_child
          .carousel-item.active
            .vasarlas__inner
              .head-title
                img[src="assets/bubble.png"]
              .vasarlas_img_inner
                img[src="assets/sec2-img1.png"]
              .vasarlas__text 
                .prod-name
                  p DOGS LOVE NONI 2db
                  p glükozaminnal, kondroitin-<br> szulfáttal és vitaminokkal 
                .prod-info
                  p Kiszerelés: <b> 2x 750 mL/doboz</b>
                  p támogatás összege: <div class="font-26 theme-text-red"><b>4.000 ft</b></div>
                .mtb-20.text-center.font-26 
                  | Ár: 29.900 Ft
                p.font-14.theme-text-white.text-center.mh-70.mh-auto-sm
                  | + kiszállítási díj, mely a <br/>  kosár tartalmához kerül <br/> hozzáadásra (2.100 Ft)
                .text-center
                  button.btn-theme-primary KOSÁRBA
          .carousel-item
            .vasarlas__inner
              .head-title
                img[src="assets/bubble.png"]
              .vasarlas_img_inner
                img[src="assets/sec2-img2.png"]
              .vasarlas__text 
                .prod-name
                  p DOGS LOVE NONI 4db
                  p glükozaminnal, kondroitin-<br> szulfáttal és vitaminokkal 
                .prod-info
                  p Kiszerelés: <b> 4x 750 mL/doboz</b>
                  p támogatás összege: <div class="font-26 theme-text-red"><b>8.000 ft</b></div>
                .mtb-20.text-center.font-26
                  | Ár: 57.900 Ft
                p.font-14.theme-text-white.text-center.mh-70.mh-auto-sm
                  | Ingyenes kiszállítás!
                .text-center
                  button.btn-theme-primary KOSÁRBA
          .carousel-item
            .vasarlas__inner
              .head-title
                img[src="assets/bubble-2.png"]
              .vasarlas_img_inner
                img[src="assets/sec2-img3.png"]
              .vasarlas__text 
                .prod-name.line-blue
                  p MAGICAL LOVE NONI 2db
                  p vörös szőlővel és<br> kék áfonyával 
                .prod-info
                  p Kiszerelés: <b> 4x 750 mL/doboz</b>
                  p támogatás összege: <div class="font-26 theme-text-blue"><b>7.200 ft</b></div>
                .mtb-20.text-center.font-26
                  | Ár: 52.800 Ft
                p.font-14.theme-text-white.text-center.mh-70.mh-auto-sm
                  | + kiszállítási díj, mely a <br/> kosár tartalmához kerül <br/> hozzáadásra (2.200 Ft)
                .text-center
                  button.btn-theme-secondary KOSÁRBA



        button.carousel-control-prev[type="button" data-target="#carouselExampleControls" data-slide="prev"]
          img[src="assets/carousel-left-indicator.svg" alt="Previous"]
        span.sr-only | Previous

        button.carousel-control-next[type="button" data-target="#carouselExampleControls" data-slide="next"]
          img[src="assets/carousel-right-indicator.svg" alt="Next"]
        span.sr-only | Next

app/views/nonis/_section3.slim
section.rendeles
  .wrapper-noni
    .common-heading.text-center
      | RENDELÉS
    br
    .sub-line.font-14.theme-text-white.text-center.mt-10.on-mobile-content
      | Ha külföldre szeretne rendelni, <br/> akkor küldjön e-mailt az 
      a.theme-text-white href="mailto:order@welovenoni.com"
        u order@welovenoni.com
      |  e-mail címre!
    br
    br
    .sub-heading
      | KOSÁR TARTALMA:
    .order-details
      .left-table
        .column-1
          p 
            b Dogs Love Noni
        .column-2
          p 1 db 2x750 ml
        .column-3
          p 29.900 ft
      .right-table
        .d-set-c.theme-text-white.mtb-30-sm
          p.theme-text-white 
            b Szállítási díj:
          p.theme-text-white
            b 2.100 ft
        .text-black
          .d-set-c
            p 
              b FIZETENDŐ:
            p.font-28-sm 
              b 32.000 ft
        .text-black
          .d-set-c
            p
             b Támogatás összege <br class="on-mobile-content"> az Alapítvány javára:
            p.no-wrap-sm.font-28-sm 
              b 4.000 ft
        
    .other-details
      .left-table.d-set.input-style
        / .vertical-separator
        .column-1
          .sub-heading
            | SZÁLLÍTÁSI INFORMÁCIÓK:
          br
          p 
            b
              | Név: 
            input type="text" placeholder="Nagy Zoltán"
          p 
            b
              | Cím: 
            input type="text" placeholder="1111 Budapest, Aradi utca 12."
          p 
            b
              | Telefonszám: 
            input type="text" placeholder="+36 30 436 7444"
          p 
            b
              | email: 
            input type="text" placeholder="nagy.zoltan@gmail.com"
          p 
            b
              | megjegyzés:
          .list-with-checkbox
            p számlázási adatok megegyeznek a szállítási adatokkal
            label.checkbox-parent
              input type="checkbox" 
              span.checkmark
          .list-with-checkbox
            p A kiszállítást a Kutyasegély szolgálat részére kérem!
            label.checkbox-parent
              input type="checkbox" checked=""
              span.checkmark
      .middle-table.d-set.input-style
        / .vertical-separator.vertical-separator2
        .column-1
          .sub-heading
            | SZÁMLÁZÁSI ADATOK:
          br
          p 
            b Név: 
            input type="text" placeholder="Nagy Zoltán"
          p 
            b Cím: 
            input type="text" placeholder="1111 Budapest, Aradi utca 12."
          p 
            b Telefonszám: 
            input type="text" placeholder="+36 30 436 7444"
          p 
            b email: 
            input type="text" placeholder="nagy.zoltan@gmail.com"
          p 
            b megjegyzés:

      .box.d-set.after-unset
        .right-table
          .column-1
            .sub-heading
              | FIZETÉSI MÓD:
            br
            .check-set
              p Utánvét (+460 Ft)
              label.checkbox-parent
                input type="checkbox" 
                span.checkmark
            .check-set  
              p bankkártya
              label.checkbox-parent
                input type="checkbox" checked=""
                span.checkmark
            .gold-btn
              button MEGRENDELEM
  p.bottom-text.on-desktop-content Ha külföldre szeretne rendelni, akkor küldjön e-mailt az <span class="link-underline">order@welovenoni.com</span> e-mail címre!""            

app/views/nonis/_section4.slim
section.teremekekrol
  .section4
    .wrapper-noni
      .left-section
        .sec4-img.on-desktop-content
          img[src="assets/group-bottle.png"]
        .sec4-img.on-mobile-content
          img[src="assets/a-terem.png"]
      .right-section
        p.heading A TERMÉKEKRŐL
        hr.separator
        p A noni egy ősi, tradicionális polinéz gyógynövény, mely fogyasztók millióinak életére hatott pozitívan, és bőségesen állnak rendelkezésre terméktapasztalatok és tudományos kutatások az állatokra gyakorolt előnyeiről, ráadásul a Dogs love NONI-t vitaminok mellett olyan ízületvédő összetevőkkel is gazdagítottuk, mint a rákpáncélból származó glükozamin és a kondroitin-szulfát cápaporcból.
        .buy-btn
          button MUTASS TÖBBET!

app/views/nonis/_section5.slim
section.befolyt
  .section5
    .leftmost-img
      img.on-desktop-content[src="assets/sec5-bg-texture.png"]
      img.on-mobile-content[src="assets/bg-texture-bottom.png"]
    .main-box
      .top-section
        .left
          p.heading.text-up A befolyt <br class="on-mobile-content"> adományból
          hr.separator
          p Gerinctörött, lebénult, balesetet szenvedett, árva kutyáknak mi jelentjük az utolsó esélyt az ÉLETHEZ. A befolyt adományokat a sérült, beteg állatok gyógykezeléseire fordítjuk, melyet nyomon követhet a Facebook oldalunkon. Elkötelezetten küzdünk a legesélytelenebbekért, és rendkívül hálásak vagyunk minden támogatásért!
          .social-img
            img[src="assets/fb.svg"]
          p Kutya-segélyszolgálat Alapítvány
          .social-images
            img[src="assets/footer-img1.png"]
            img[src="assets/footer-img2.png"]
            img[src="assets/footer-img3.png"]
            img[src="assets/footer-img4.png"]
        .right
          img[src="assets/sec5-img.png"]
      

      /// copyright section
      .bottom-section
        .box
          .logo
            img[src="assets/logo.svg"]
          .links
            .list-link
              div
                a href="/"
                  | visszáru Szabályzat
              div
                a href="/"
                  | www.welovenoni.com
              div
                a href="/"
                  | Adatkezelési irányelvek
            .copyright-text
              | Copyright @ <br class="on-mobile-content"> 2023 We Love Noni.

app/views/nonis/edit.html.erb
<h1>Editing Noni</h1>

<%= render 'form', noni: @noni %>

<%= link_to 'Show', @noni %> |
<%= link_to 'Back', nonis_path %>

app/views/nonis/index.html.erb
<div>
  <%= render partial: 'section1' %>
  <%= render partial: 'section2' %>
  <%= render partial: 'section3' %>
  <%= render partial: 'section4' %>
  <%= render partial: 'section5' %>
</div>

app/views/nonis/new.html.erb
<h1>New Noni</h1>

<%= render 'form', noni: @noni %>

<%= link_to 'Back', nonis_path %>

app/views/nonis/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_noni_path(@noni) %> |
<%= link_to 'Back', nonis_path %>